# Author: Cavelle Benjamin

variables:
  # LC_ALL: "en_US.UTF-8"
  # LANG: "en_US.UTF-8"
  CI: ""
  DOMAIN: "thecb4.io"
  EMAIL: "cavelle@thecb4.io"

stages:
  - build-test
  # - docs
  # - release

spm_514_xenial:
  image:
    name: swift:5.1.4-xenial
    entrypoint: [""]
  stage: build-test
  script:
    - swift package update
    - swift test --enable-code-coverage
    # - swift build --build-tests -c debug
    # - swift test -c debug
    # - swift build -c release
  only:
    - master

# spm_501_bonic:
#   image:
#     name: swift:5.0.1-bionic
#     entrypoint: [""]
#   stage: build-test
#   script:
#     - swift package update
#     - swift test --generate-linuxmain
#     - swift build --build-tests -c debug
#     - swift test -c debug
#     - swift build -c release
#   only:
#     - master

# xcode_501_macOS:
#   stage: build
#   script:
#     - xcodebuild clean -project ProjectName.xcodeproj -scheme SchemeName | xcpretty
#     - xcodebuild test -project ProjectName.xcodeproj -scheme SchemeName -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.2' | xcpretty -s
#   tags:
#     - ios_9-2
#     - xcode_7-2
#     - osx_10-11

# pages:
#   image:
#     name: alpine:latest
#   stage: docs
#   dependencies:
#     - spm_514_xenial
#     # - spm_501_bonic
#   script:
#     - mkdir public
#     - cp -a docs/api/. public/
#   artifacts:
#     paths:
#     - public
#   only:
#     - master
