version: "3.7"

services:
  swift-linux:
    image: thecb4/swift-plus:latest
    command:
      - /bin/sh
      - -c
      - |
        mkdir /tmp/git
        cd /tmp/git
        git clone https://gitlab.com/thecb4/shellkit.git
        cd shellkit
        ./calm.swift work