version: "3.7"

services:
  swift-linux:
    image: thecb4/swift-plus:5.2-xenial
    command:
      - /bin/sh
      - -c
      - |
        cd /calm
        ./calm.swift work test
    volumes:
      - ./:/calm