#if !canImport(ObjectiveC)
  import XCTest

  extension CommandTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommandTests = [
      ("testCreateCommand", testCreateCommand)
    ]
  }

  extension ShellTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ShellTests = [
      ("testCopy", testCopy),
      ("testCreateShell", testCreateShell),
      ("testEcho", testEcho),
      ("testExecute", testExecute),
      ("testGitListFiles", testGitListFiles),
      ("testGitListModifiedFiles", testGitListModifiedFiles),
      ("testGitListUntrackedFiles", testGitListUntrackedFiles),
      ("testRm", testRm),
      ("testShellName", testShellName)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    [
      testCase(CommandTests.__allTests__CommandTests),
      testCase(ShellTests.__allTests__ShellTests)
    ]
  }
#endif
